# Generated by Django 4.1.5 on 2023-01-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='event',
            name='weather',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
